name: Run foxygfw

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Update package list
      run: sudo apt update

    - name: Install git and python3-venv
      run: sudo apt install git python3-venv -y

    - name: Clone foxygfw repository
      run: git clone https://github.com/lsr0LSR/foxygfw.git foxygfw

    - name: Set up and run the script
      working-directory: foxygfw
      run: |
        cp config.ini.example config.ini
        python3 -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
        python main.py
        deactivate

    - name: Upload output.json
      uses: actions/upload-artifact@v3
      with:
        name: output-json
        path: foxygfw/output.json
