name: Run foxygfw from release

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag to use'
        required: true
        default: 'v1.0.0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Update package list
        run: sudo apt update

      - name: Install git and python3-venv
        run: sudo apt install git python3-venv -y

      - name: Download foxygfw release
        run: |
          git clone https://github.com/scp-079/foxygfw.git foxygfw

      - name: Set up and run the script
        working-directory: foxygfw
        run: |
          cp config.ini.example config.ini
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          python main.py
          deactivate
          git tag "${{ github.event.inputs.release_tag }}"
          
      - name: Create Release
        uses: softprops/action-gh-release@v2.2.1
        with:
          tag_name: ${{ github.event.inputs.output_tag }}
          name: Output from ${{ github.event.inputs.release_tag }}
          body: |
            This release contains the output.json generated from release ${{ github.event.inputs.release_tag }} of lsr0LSR/foxygfw.
          files: foxygfw/output.json
          fail_on_unmatched_files: true
          generate_release_notes: false
          make_latest: true
